# Development Configuration
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:SalesOrderDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: EMBEDDED
    platform: h2
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: true
        web-allow-others: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

# Actuator
manangement:
  health:
    status:
      order: FATAL, DOWN, OUT_OF_SERVICE, WARN, UP
      http-mapping:
        WARN: 200
  endpoint:
    health:
      show-details: always
    restart:
      enabled: true
    resume:
      enabled: true
    pause:
      enabled: true
    shutdown:
      enabled: true
    configprops:
      keys-to-sanitize: password,secret,key,token,.*credentials.*,vcap_services,sun.java.command
    env:
      keys-to-sanitize: password,secret,key,token,.*credentials.*,vcap_services,sun.java.command
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
    
# Logging
logging:
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR
    com:
      sales:
        order: WARN

# Filter
gui:
  protocol: http
  host: localhost
  port: 3000
  
# Dev Setup
server:
  servlet:
    context-path: /bankservice
  port: 9090